/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Dict_DictApp2_DictSearchEngine */

#ifndef _Included_com_Dict_DictApp2_DictSearchEngine
#define _Included_com_Dict_DictApp2_DictSearchEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_Dict_DictApp2_DictSearchEngine
 * Method:    dictEngQueryWord
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_Dict_DictApp2_DictSearchEngine_dictEngQueryWord (JNIEnv *, jclass, jstring);

/*
 * Class:     com_Dict_DictApp2_DictSearchEngine
 * Method:    dictEngAddDictionary
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Dict_DictApp2_DictSearchEngine_dictEngAddDictionary (JNIEnv *, jclass, jstring); 
/*
 * Class:     com_Dict_DictApp2_DictSearchEngine
 * Method:    dictEngRemoveDictionary
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Dict_DictApp2_DictSearchEngine_dictEngRemoveDictionary (JNIEnv *, jclass, jstring); 
/*
 * Class:     com_Dict_DictApp2_DictSearchEngine
 * Method:    dictEngScanPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_Dict_DictApp2_DictSearchEngine_dictEngScanPath (JNIEnv *, jclass, jstring); 
/*
 * Class:     com_Dict_DictApp2_DictSearchEngine
 * Method:    dictEngInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_Dict_DictApp2_DictSearchEngine_dictEngInit (JNIEnv *, jclass); 
/*
 * Class:     com_Dict_DictApp2_DictSearchEngine
 * Method:    dictEngDeinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_Dict_DictApp2_DictSearchEngine_dictEngDeinit (JNIEnv *, jclass); 
/*
 * Class:     com_Dict_DictApp2_DictSearchEngine
 * Method:    dictEngGetDictList
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_Dict_DictApp2_DictSearchEngine_dictEngGetDictList (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
