/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Dict_DictApp2_DictSearchEngine_Callbacks */

#ifndef _Included_com_Dict_DictApp2_DictSearchEngine_Callbacks
#define _Included_com_Dict_DictApp2_DictSearchEngine_Callbacks
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
