/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Dict_DictApp2_DictSearchEngine */

#ifndef _Included_com_Dict_DictApp2_DictSearchEngine
#define _Included_com_Dict_DictApp2_DictSearchEngine
#ifdef __cplusplus
extern "C" {
#endif
#undef com_Dict_DictApp2_DictSearchEngine_MESSAGE_MEANING_ARRIVING
#define com_Dict_DictApp2_DictSearchEngine_MESSAGE_MEANING_ARRIVING 0L
/*
 * Class:     com_Dict_DictApp2_DictSearchEngine
 * Method:    engQueryWord
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_Dict_DictApp2_DictSearchEngine_engQueryWord
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_Dict_DictApp2_DictSearchEngine
 * Method:    engAsyncQueryWord
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_Dict_DictApp2_DictSearchEngine_engAsyncQueryWord
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_Dict_DictApp2_DictSearchEngine
 * Method:    engAddDictionary
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Dict_DictApp2_DictSearchEngine_engAddDictionary
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_Dict_DictApp2_DictSearchEngine
 * Method:    engRemoveDictionary
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Dict_DictApp2_DictSearchEngine_engRemoveDictionary
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
