
top_builddir=$(PWD)
export top_builddir
CHARSETDIR=$(top_builddir)/charset
SOURCEDIR=$(top_builddir)/src

all:
	cd $(CHARSETDIR) && make;cd $(SOURCEDIR) && make;


clean:
	cd $(CHARSETDIR) && make clean;cd $(SOURCEDIR) && make clean;


